import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex p-10 justify-between">
          <h2 className="text-lg font-black">
            <Link href='/blog'>
              Blogs
            </Link>
          </h2>

          <nav className="flex gap-5">
            
            <Link href='/login'>
              Login
            </Link>
            <Link href='/register'>
              Register
            </Link>

          </nav>
        </header>
        <div className="flex flex-col gap-10 mx-auto container">

        {children}
        </div>
      </body>
    </html>
  );
}
